/**
 * Build configuration for a site that has to work from a directory it does not know the name of.
 *
 * GitHub Pages serves a project repository at `https://user.github.io/repository/`, so every asset
 * URL the build emits has to resolve from there rather than from `/`. The default `base` is
 * therefore `./` — relative — which resolves correctly at the root, at `/repository/`, at a
 * deep-linked `/repository/index.html`, and from a `file://` copy on a USB stick. `BASE_PATH` is
 * available for a deployment that genuinely needs an absolute prefix, and `npm run build` is
 * verified at a non-root base in the test suite.
 *
 * The consequence is that the application must never rely on path-based routing: there is no server
 * to rewrite `/repository/game/42` back onto `index.html`, and a reload of such a URL is a Pages
 * 404. Application state lives in the URL fragment (see `Routing`), which no server ever sees.
 */
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { createHash } from 'node:crypto';

/**
 * Emit the service worker with the exact asset list this build produced.
 *
 * Written as a plugin rather than shipped as a static file because a precache list has to name the
 * content-hashed bundles, and those names are not known until the bundle exists. The cache name
 * carries a digest of that same list, so a build that changes anything gets a new cache and the
 * previous one is deleted on activation — which is what keeps a stale worker from pinning an old
 * application on a Chromebook that has been open all season.
 */
function serviceWorkerPlugin(): Plugin {
  return {
    name: 'standalone-scorekeeper-service-worker',
    apply: 'build',
    enforce: 'post',
    generateBundle(_options, bundle) {
      const emitted = Object.keys(bundle).filter((name) => !name.endsWith('.map'));
      // Files copied straight from `public/` are not part of the bundle and have to be named. They
      // are also not content-hashed, which is why the cache name is derived from the whole list.
      const staticFiles = ['index.html', 'manifest.webmanifest', 'icon.svg', 'icon-maskable.svg'];
      const precache = [...new Set([...staticFiles, ...emitted])].sort();
      const buildId = createHash('sha256').update(precache.join('\n')).digest('hex').slice(0, 16);
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: serviceWorkerSource(buildId, precache),
      });
    },
  };
}

function serviceWorkerSource(buildId: string, precache: string[]): string {
  return `/* Generated by vite.config.ts. Do not edit. */
const CACHE = 'scoresheet-shell-${buildId}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      // Relative to the worker's own URL, so the same file works at any base path. One asset that
      // will not cache must not fail the install and leave the room with no offline shell at all.
      Promise.all(
        PRECACHE.map((asset) =>
          cache.add(new Request(new URL(asset, self.registration.scope), { cache: 'reload' })).catch(() => undefined),
        ),
      ),
    ),
  );
  // A new build supersedes the old one immediately. The page already running keeps the code it
  // loaded; only the next load changes, so this cannot swap anything under an active game.
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('message', (event) => {
  if (event.data === 'scoresheet:skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Tournament control is a different origin and its answers are never authoritative from a cache:
  // a stale assignment or a replayed submission verdict is worse than an honest network error.
  if (url.origin !== self.location.origin) return;
  // Same-origin non-shell requests (there are none today) are left alone for the same reason.
  if (!url.pathname.startsWith(new URL(self.registration.scope).pathname)) return;

  if (request.mode === 'navigate') {
    // Network first, so a deployed update is picked up the moment the room is online, with the
    // cached shell behind it so a dead network still opens the scoresheet.
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(new URL('index.html', self.registration.scope), copy));
          return response;
        })
        .catch(() =>
          caches
            .match(new URL('index.html', self.registration.scope))
            .then((cached) => cached ?? Response.error()),
        ),
    );
    return;
  }

  // Built assets are content-hashed, so a hit is the right file by construction.
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
`;
}

export default defineConfig({
  base: process.env.BASE_PATH ?? './',
  plugins: [react(), serviceWorkerPlugin()],
  build: {
    // A room's Chromebook is not a phone on a train; a slightly larger single chunk that is
    // guaranteed present offline beats several that might not all have been cached.
    chunkSizeWarningLimit: 1500,
  },
});
