/**
 * Quizbowl Resource Center-compatible HTML stat reports (issue #762, epic #760).
 *
 * The Resource Center (hsquizbowl.org/db) accepts HTML reports generated by SQBS or YellowFruit.
 * This module is the dedicated exporter for that upload contract. It is deliberately separate
 * from the general-purpose printable QBSheet report ZIP: the two share the canonical stats
 * snapshot DTO and the existing rules-aware render helpers, but Resource Center compatibility
 * is an explicit, tested contract here rather than a side effect of printable output.
 *
 * Verified public report shape (September 2026): the Resource Center exposes six views for an
 * accepted report — Standings, Individuals, Scoreboard, Team Detail, Player Detail, and Round
 * Report. Those six roles are first-class below and required for upload. A dynamic `_statkey`
 * companion is generated for SQBS completeness/interoperability but is NOT a required upload
 * slot: current public navigation and upload instructions expose no Stat Key field, so it must
 * not block a director until the live authenticated upload form proves otherwise (#764).
 *
 * Reference: a current accepted YellowFruit report, `resourceCenterReference` below.
 *
 * Canonical-stats semantics: every number comes from the caller's `StatsSnapshot` — the same
 * accepted-results snapshot Director/Live/CSV render. This module never recalculates standings,
 * never consults Director state or raw QBJ, and never converts an honest unknown (null) into a
 * legitimate zero; unknown cells render as `—` via the shared report helpers.
 *
 * "Resource Center compatible" labeling: the structure here targets the accepted SQBS/YellowFruit
 * conventions (conventional `<base>_<role>.html` suffixes, document/head/table structure,
 * escaping), but the label must wait for the real-upload smoke test in #764. Network upload
 * itself is an explicit non-goal of #762.
 */

import { renderBoxScoreReport } from './boxScoreReport.js';
import { renderPlayerDetailReport } from './playerDetailReport.js';
import { renderReportPage, reportEscape, reportScopeNote } from './reportHtml.js';
import { reportPresentationOf, reportUnknown, type ReportPresentation } from './reportPresentation.js';
import {
  renderRulesAwareIndividuals,
  renderRulesAwareRounds,
  renderRulesAwareStandings,
} from './rulesAwareReport.js';
import type { StatsSnapshot } from './stats.js';
import { renderTeamDetailReport } from './teamDetailReport.js';
import type { FormatError, FormatWarning } from './types.js';

/**
 * Semantic upload role of one report file. `scoreboard` is the per-game box-score view the
 * Resource Center calls "Scoreboard" (the `*_games.html` file); `statKey` is the optional
 * companion, never a required upload slot.
 */
export type ResourceCenterReportKind =
  'standings' | 'individuals' | 'scoreboard' | 'teamDetail' | 'playerDetail' | 'rounds' | 'statKey';

/** The six verified public Resource Center views, in upload-form order. */
export const resourceCenterRequiredKinds: readonly ResourceCenterReportKind[] = [
  'standings',
  'individuals',
  'scoreboard',
  'teamDetail',
  'playerDetail',
  'rounds',
];

/** Every kind the exporter can emit, required roles first. */
export const resourceCenterAllKinds: readonly ResourceCenterReportKind[] = [
  ...resourceCenterRequiredKinds,
  'statKey',
];

/**
 * Conventional SQBS/YellowFruit-compatible filename suffixes. These mirror the report
 * filenames QBSheet's own SQBS tournament serializer advertises in its settings section
 * (`packages/tournament-formats/src/sqbs.ts`): the Resource Center upload walkthrough maps
 * its `Scoreboard` field to the report ending in `_games.html`.
 */
export const resourceCenterSuffixes: Record<ResourceCenterReportKind, string> = {
  standings: '_standings.html',
  individuals: '_individuals.html',
  scoreboard: '_games.html',
  teamDetail: '_teamdetail.html',
  playerDetail: '_playerdetail.html',
  rounds: '_rounds.html',
  statKey: '_statkey.html',
};

/** Resource Center vocabulary for navigation and upload-slot labeling. */
export const resourceCenterRoleLabels: Record<ResourceCenterReportKind, string> = {
  standings: 'Standings',
  individuals: 'Individuals',
  scoreboard: 'Scoreboard',
  teamDetail: 'Team Detail',
  playerDetail: 'Player Detail',
  rounds: 'Round Report',
  statKey: 'Stat Key',
};

/**
 * Current accepted YellowFruit report documenting the six-view public shape. Kept in code
 * (not only docs) so structural tests can pin the contract to a real-world reference.
 */
export const resourceCenterReference = {
  url: 'https://hsquizbowl.org/db/tournaments/10615/stats/all_games/',
  generator: 'YellowFruit',
  views: ['Standings', 'Individuals', 'Scoreboard', 'Team Detail', 'Player Detail', 'Round Report'],
  note: 'The public report navigation exposes no separate Stat Key view; treat statKey as an optional companion until the authenticated upload form proves otherwise.',
} as const;

export interface ResourceCenterReportFile {
  kind: ResourceCenterReportKind;
  /** False only for the optional statKey companion. */
  requiredForResourceCenter: boolean;
  fileName: string;
  content: string;
}

export interface ResourceCenterReportArtifact {
  scopeLabel: string;
  baseName: string;
  files: ResourceCenterReportFile[];
  warnings: FormatWarning[];
  errors: FormatError[];
}

export interface ResourceCenterReportOptions {
  /** Tournament-derived when omitted; always sanitized via sanitizeResourceCenterBaseName. */
  baseName?: string;
  /** Default true: emit the optional statKey companion alongside the six required roles. */
  includeStatKey?: boolean;
}

const MAX_BASE_NAME_LENGTH = 80;

/**
 * Sanitize a report-set base name predictably. Unicode letters and numbers survive (NFC
 * normalized so composed/decomposed spellings map identically); path separators, controls,
 * filesystem-reserved characters (`<>:"/\|?*`), and all other punctuation/whitespace runs
 * collapse to one hyphen. Empty input falls back to `'report'`, so every report set still
 * shares one stable, filesystem-safe prefix.
 */
export function sanitizeResourceCenterBaseName(value: string): string {
  const normalized = value.normalize('NFC').trim();
  if (!normalized) return 'report';
  const withoutReserved = normalized.replace(/[<>:"/\\|?*]+/g, '-').replace(/\p{Cc}+/gu, '-');
  const hyphenated = withoutReserved
    .replace(/[^\p{L}\p{N}._-]+/gu, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^[._-]+|[._-]+$/g, '')
    .slice(0, MAX_BASE_NAME_LENGTH)
    .replace(/[._-]+$/, '');
  return hyphenated || 'report';
}

/** Stable upload filename for one semantic role: `<base><suffix>`. */
export function resourceCenterFileName(baseName: string, kind: ResourceCenterReportKind): string {
  return `${sanitizeResourceCenterBaseName(baseName)}${resourceCenterSuffixes[kind]}`;
}

/** Filenames for every kind in one report set; the base prefix is identical for all files. */
export function resourceCenterFileNames(baseName: string): Record<ResourceCenterReportKind, string> {
  const clean = sanitizeResourceCenterBaseName(baseName);
  return {
    standings: `${clean}${resourceCenterSuffixes.standings}`,
    individuals: `${clean}${resourceCenterSuffixes.individuals}`,
    scoreboard: `${clean}${resourceCenterSuffixes.scoreboard}`,
    teamDetail: `${clean}${resourceCenterSuffixes.teamDetail}`,
    playerDetail: `${clean}${resourceCenterSuffixes.playerDetail}`,
    rounds: `${clean}${resourceCenterSuffixes.rounds}`,
    statKey: `${clean}${resourceCenterSuffixes.statKey}`,
  };
}

/** Printable-report filenames the shared renderers link to; rebased to upload filenames below. */
const printableFileNames = {
  standings: 'standings.html',
  individuals: 'individuals.html',
  scoreboard: 'games.html',
  teamDetail: 'teamdetail.html',
  playerDetail: 'playerdetail.html',
  rounds: 'rounds.html',
} as const satisfies Record<Exclude<ResourceCenterReportKind, 'statKey'>, string>;

/**
 * Navigation for one report set, in Resource Center vocabulary. `index.html` is intentionally
 * absent: it belongs to the general printable report and is not a Resource Center upload slot.
 */
function resourceCenterNav(
  fileNames: Record<ResourceCenterReportKind, string>,
  kinds: readonly ResourceCenterReportKind[],
): string {
  const items = kinds
    .map((kind) => `<li><a href="${fileNames[kind]}">${resourceCenterRoleLabels[kind]}</a></li>`)
    .join('');
  return `<nav aria-label="Resource Center reports"><ul>${items}</ul></nav>`;
}

/**
 * Rebase shared-renderer output onto upload filenames: rewrite printable cross-links to the
 * `<base>_<role>.html` names and swap the printable nav (Index/Games/Rounds/Teams/Players)
 * for the Resource Center nav (Scoreboard/Team Detail/Player Detail/Round Report/…). Page
 * bodies — and every number in them — pass through untouched.
 */
function rebaseReportLinks(
  content: string,
  fileNames: Record<ResourceCenterReportKind, string>,
  kinds: readonly ResourceCenterReportKind[],
): string {
  // Rebase body cross-links first: upload filenames contain the printable names as
  // substrings (`<base>_standings.html` contains `standings.html`), so the nav swap must
  // come last or its already-correct hrefs would be prefixed a second time.
  let rebased = content;
  const pairs: Array<[string, string]> = [
    [printableFileNames.standings, fileNames.standings],
    [printableFileNames.individuals, fileNames.individuals],
    [printableFileNames.scoreboard, fileNames.scoreboard],
    [printableFileNames.teamDetail, fileNames.teamDetail],
    [printableFileNames.playerDetail, fileNames.playerDetail],
    [printableFileNames.rounds, fileNames.rounds],
  ];
  for (const [from, to] of pairs) {
    if (from !== to) rebased = rebased.split(from).join(to);
  }
  return rebased.replace(/<nav aria-label="Stat reports">.*?<\/nav>/s, resourceCenterNav(fileNames, kinds));
}

/**
 * Build the Resource Center report set for one canonical snapshot.
 *
 * Each of the six required roles renders through the same rules-aware renderer the printable
 * report uses, so standings/individuals/scoreboard/team/player/round numbers cannot drift
 * from Director/Live/CSV. Accepted/current results only, supersession, cancelled-game
 * exclusion, forfeits, ties/overtime, final-placement ranks, honest unknown-vs-zero, and
 * scoring definitions all arrive via the snapshot; nothing is recalculated here.
 *
 * Navigation is scoped to the six verified Resource Center upload slots: required pages
 * link only among destinations that exist after those six files are uploaded. The optional
 * `_statkey.html` companion is still emitted by default for SQBS interoperability but is
 * never a navigation destination of a required page (and carries the same six-link nav
 * itself so every uploadable link resolves within the published set).
 */
export function buildResourceCenterReport(
  snapshot: StatsSnapshot,
  options: ResourceCenterReportOptions = {},
): ResourceCenterReportArtifact {
  const baseName = sanitizeResourceCenterBaseName(options.baseName ?? snapshot.tournament.name);
  const presentation = reportPresentationOf(snapshot);
  const scopeLabel =
    typeof presentation.metadata.scopeLabel === 'string' && presentation.metadata.scopeLabel
      ? presentation.metadata.scopeLabel
      : 'Overall';
  const includeStatKey = options.includeStatKey ?? true;
  const kinds: readonly ResourceCenterReportKind[] = includeStatKey
    ? resourceCenterAllKinds
    : resourceCenterRequiredKinds;
  const fileNames = resourceCenterFileNames(baseName);
  const rendered: Record<ResourceCenterReportKind, string | null> = {
    standings: renderRulesAwareStandings(snapshot),
    individuals: renderRulesAwareIndividuals(snapshot),
    scoreboard: renderBoxScoreReport(snapshot),
    teamDetail: renderTeamDetailReport(snapshot),
    playerDetail: renderPlayerDetailReport(snapshot),
    rounds: renderRulesAwareRounds(snapshot),
    statKey: includeStatKey ? renderResourceCenterStatKey(snapshot) : null,
  };
  const files: ResourceCenterReportFile[] = kinds.map((kind) => ({
    kind,
    requiredForResourceCenter: kind !== 'statKey',
    fileName: fileNames[kind],
    content: rebaseReportLinks(rendered[kind] as string, fileNames, resourceCenterRequiredKinds),
  }));
  const warnings: FormatWarning[] = [];
  const errors: FormatError[] = [];
  return { scopeLabel, baseName, files, warnings, errors };
}

interface StatKeyRow {
  abbr: string;
  meaning: string;
}

function answerTierRows(presentation: ReportPresentation): StatKeyRow[] {
  return presentation.answerColumns.map((column) => {
    const valueText =
      column.pointValue !== null
        ? `${column.pointValue} pts`
        : column.pointValues.length > 1
          ? `mixed values ${column.pointValues.join(', ')} (grouped by category, not point value)`
          : 'point value unavailable';
    const abbr =
      column.pointValue !== null
        ? `${column.shortLabel} (${column.pointValue})`
        : column.pointValues.length > 1
          ? `${column.shortLabel} (${column.pointValues.join('/')})`
          : column.shortLabel;
    return { abbr, meaning: `${column.label} answers · ${valueText}` };
  });
}

/**
 * One honest sentence about the tournament's own point values. Tiers without a single agreed
 * value (mixed definitions, legacy snapshots) stay in the table above with their mixed-value
 * note instead of being forced into this sentence.
 */
function scoringLine(presentation: ReportPresentation): string {
  const known = presentation.answerColumns.filter(
    (column): column is typeof column & { pointValue: number } => column.pointValue !== null,
  );
  if (known.length === 0) return "Points are scored under the tournament's own definitions.";
  const values = known.map((column) => `${column.pointValue} per ${column.label.toLowerCase()}`);
  return `Points are scored under the tournament's own definitions: ${values.join(' · ')}.`;
}

/**
 * Render the optional `_statkey.html` companion for SQBS completeness/interoperability.
 *
 * Every row is derived from the snapshot's own presentation contract, so the key documents
 * only abbreviations and columns this report set actually emits: answer tiers that exist
 * under the tournament's scoring definitions, the active points metric, bonuses/bouncebacks/
 * lightning/overtime only when applicable and recorded. Columns the report does not contain
 * are never described.
 */
export function renderResourceCenterStatKey(snapshot: StatsSnapshot): string {
  const presentation = reportPresentationOf(snapshot);
  const rows: StatKeyRow[] = [
    { abbr: 'W', meaning: 'Wins' },
    { abbr: 'L', meaning: 'Losses' },
  ];
  if (snapshot.teams.some((row) => row.ties > 0)) {
    rows.push({ abbr: 'T', meaning: 'Ties (the record column shows W–L–T only for teams that have tied)' });
  }
  rows.push({ abbr: 'GP', meaning: 'Games played' });
  if (presentation.options.showPointsForAgainstMargin) {
    rows.push(
      { abbr: 'PF', meaning: 'Points for (total points scored)' },
      { abbr: 'PA', meaning: 'Points against (total points allowed)' },
      { abbr: 'Margin', meaning: 'Scoring margin (PF minus PA)' },
    );
  }
  const metricLabel =
    presentation.options.pointsMetric === 'pointsPerX'
      ? (presentation.pointsNormalization?.label ?? 'Pts/X')
      : 'PPG';
  rows.push({
    abbr: metricLabel,
    meaning:
      presentation.options.pointsMetric === 'pointsPerX'
        ? 'Points per game normalized to the regulation tossup count'
        : 'Points per game',
  });
  if (presentation.options.showPapg) {
    rows.push({ abbr: 'PAPG', meaning: 'Points allowed per game' });
  }
  rows.push(
    { abbr: 'TUH', meaning: 'Tossups heard' },
    { abbr: 'PPTUH', meaning: 'Points per tossup heard (shown as — when tossups-heard is unknown)' },
  );
  rows.push(...answerTierRows(presentation));
  if (presentation.applicability.bonuses) {
    rows.push(
      { abbr: 'BH', meaning: 'Bonuses heard' },
      { abbr: 'BP', meaning: 'Bonus points' },
      { abbr: 'PPB', meaning: 'Points per bonus (shown as — when no bonuses were heard)' },
    );
  }
  if (presentation.applicability.bouncebacks) {
    rows.push({ abbr: 'Bouncebacks', meaning: 'Bounceback points (rebounded bonus parts)' });
  }
  if (presentation.applicability.lightning) {
    rows.push({ abbr: 'Lightning', meaning: 'Lightning-round points' });
  }
  if (presentation.applicability.overtime) {
    rows.push({
      abbr: 'Overtime',
      meaning: 'Games decided after regulation list their overtime tossups on the Scoreboard page',
    });
  }
  const body =
    `${reportScopeNote(snapshot)}` +
    `<p class="meta">Abbreviations used in this report set. Only columns this tournament's ` +
    `rules actually produce are listed.</p>` +
    `<div class="table-wrap"><table><caption>Stat key</caption><thead><tr>` +
    `<th scope="col">Abbreviation</th><th scope="col">Meaning</th>` +
    `</tr></thead><tbody>` +
    rows
      .map((row) => `<tr><td>${reportEscape(row.abbr)}</td><td>${reportEscape(row.meaning)}</td></tr>`)
      .join('') +
    `</tbody></table></div>` +
    (presentation.mixedDefinitionNote
      ? `<p class="report-note">${reportEscape(presentation.mixedDefinitionNote)}</p>`
      : '') +
    `<p class="meta">${reportEscape(reportUnknown)} means the accepted result did not record ` +
    `that statistic. It is never a silent zero: rates that need an unknown denominator are ` +
    `withheld, not estimated.</p>` +
    `<p class="meta">${reportEscape(scoringLine(presentation))}</p>`;
  return renderReportPage(snapshot, 'Stat Key', body);
}
